import { Stock } from "./types";

export const MOCK_STOCKS: Stock[] = [
  // GLOBAL
  {
    id: "1",
    ticker: "AAPL",
    name: "Apple Inc.",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 189.45,
    targetPrice: 210.00,
    marketCap: 2900,
    peRatio: 28.5,
    pbRatio: 35.8,
    roe: 154,
    pegRatio: 2.1,
    dividendYield: 0.5,
    volume24h: 55.4,
    ema50: 185.20,
    ema200: 178.50,
    industry: "Consumer Electronics",
    description: "Creadores de los iPhones y Mac. Es una de las empresas más valiosas y seguras del mundo."
  },
  {
    id: "2",
    ticker: "MSFT",
    name: "Microsoft Corp.",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 412.30,
    targetPrice: 480.00,
    marketCap: 3050,
    peRatio: 36.2,
    pbRatio: 12.4,
    roe: 38.5,
    pegRatio: 2.4,
    dividendYield: 0.7,
    volume24h: 22.1,
    ema50: 405.10,
    ema200: 385.40,
    industry: "Software",
    description: "Líder en computación en la nube (Azure) y programas de oficina (Office) para todo el mundo."
  },
  {
    id: "3",
    ticker: "GOOGL",
    name: "Alphabet Inc.",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 165.20,
    targetPrice: 190.00,
    marketCap: 2050,
    peRatio: 24.1,
    pbRatio: 7.2,
    roe: 27.3,
    pegRatio: 1.1,
    dividendYield: 0.4,
    volume24h: 18.5,
    ema50: 160.20,
    ema200: 152.10,
    industry: "Internet Services",
    description: "La empresa dueña de Google y YouTube. Es el corazón de la publicidad e internet."
  },
  {
    id: "4",
    ticker: "NVDA",
    name: "NVIDIA Corp.",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 890.15,
    targetPrice: 1100.00,
    marketCap: 2200,
    peRatio: 74.2,
    pbRatio: 45.1,
    roe: 91.5,
    pegRatio: 1.2,
    dividendYield: 0.02,
    volume24h: 450.2,
    ema50: 820.50,
    ema200: 650.30,
    industry: "Semiconductors",
    description: "Los cerebros detrás de la Inteligencia Artificial. Fabrican los chips que mueven el futuro."
  },
  {
    id: "5",
    ticker: "META",
    name: "Meta Platforms",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 475.10,
    targetPrice: 530.00,
    marketCap: 1200,
    peRatio: 26.5,
    pbRatio: 7.8,
    roe: 28.1,
    pegRatio: 0.8,
    dividendYield: 0.4,
    volume24h: 15.2,
    ema50: 460.10,
    ema200: 410.50,
    industry: "Social Media",
    description: "Dueños de Facebook, Instagram y WhatsApp. Conectan a miles de millones de personas."
  },
  // ARGENTINA (ADRs usually valued in USD)
  {
    id: "6",
    ticker: "MELI",
    name: "MercadoLibre Inc.",
    market: "Argentina",
    assetType: "Acción",
    baseCurrency: "ARS",
    price: 19230.00,
    targetPrice: 24000.00,
    marketCap: 102.5,
    peRatio: 45.2,
    pbRatio: 24.5,
    roe: 35.2,
    pegRatio: 0.9,
    dividendYield: 0.0,
    volume24h: 1.2,
    ema50: 18500.50,
    ema200: 16200.30,
    industry: "E-Commerce",
    description: "Líder en comercio online en Latam. Muy innovador tanto en ventas como en pagos digitales (Mercado Pago)."
  },
  {
    id: "7",
    ticker: "GGAL",
    name: "Grupo Fin. Galicia",
    market: "Argentina",
    assetType: "Acción",
    baseCurrency: "ARS",
    price: 6345.00,
    targetPrice: 8200.00,
    marketCap: 4.8,
    peRatio: 6.5,
    pbRatio: 1.4,
    roe: 22.4,
    pegRatio: 0.4,
    dividendYield: 4.5,
    volume24h: 0.8,
    ema50: 5900.00,
    ema200: 4800.00,
    industry: "Banking",
    description: "Uno de los bancos privados más importantes de Argentina. Clave para el sistema financiero local."
  },
  {
    id: "8",
    ticker: "YPFD",
    name: "YPF S.A.",
    market: "Argentina",
    assetType: "Acción",
    baseCurrency: "ARS",
    price: 32450.00,
    targetPrice: 45000.00,
    marketCap: 9.5,
    peRatio: 3.2,
    pbRatio: 0.8,
    roe: 18.5,
    pegRatio: 0.2,
    dividendYield: 2.1,
    volume24h: 1.1,
    ema50: 30100.00,
    ema200: 25400.00,
    industry: "Oil & Gas",
    description: "La joya energética de Argentina. Líder en petróleo y gas en Vaca Muerta."
  },
  {
    id: "9",
    ticker: "PAMP",
    name: "Pampa Energía S.A.",
    market: "Argentina",
    assetType: "Acción",
    baseCurrency: "ARS",
    price: 4850.00,
    targetPrice: 6200.00,
    marketCap: 3.1,
    peRatio: 5.4,
    pbRatio: 1.2,
    roe: 14.2,
    pegRatio: 0.5,
    dividendYield: 0.0,
    volume24h: 0.4,
    ema50: 4600.00,
    ema200: 4100.00,
    industry: "Utilities",
    description: "Empresa de energía muy eficiente que genera electricidad para millones de hogares."
  },
  {
    id: "10",
    ticker: "TGSU2",
    name: "Transportadora Gas del S.",
    market: "Argentina",
    assetType: "Acción",
    baseCurrency: "ARS",
    price: 4200.00,
    targetPrice: 5500.00,
    marketCap: 3.2,
    peRatio: 8.4,
    pbRatio: 1.8,
    roe: 16.8,
    pegRatio: 0.7,
    dividendYield: 1.5,
    volume24h: 0.2,
    ema50: 3950.00,
    ema200: 3500.00,
    industry: "Energy Infrastructure",
    description: "Transportan el gas que mueve al país. Es una infraestructura vital y muy estable."
  },
  // NUEVOS ACTIVOS NACIONALES
  {
    id: "11",
    ticker: "AL30",
    name: "Bonos Soberanos 2030",
    market: "Argentina",
    assetType: "Bono",
    baseCurrency: "ARS",
    price: 52450.00,
    targetPrice: 65000.00,
    marketCap: 15,
    peRatio: 0,
    pbRatio: 0,
    roe: 0,
    pegRatio: 0,
    dividendYield: 12.5,
    volume24h: 150,
    ema50: 51200.20,
    ema200: 48500.10,
    industry: "Estado Nacional",
    description: "Bono del Estado Argentino. Es una de las herramientas más operadas para cobertura y renta."
  },
  {
    id: "12",
    ticker: "YMCQD",
    name: "ON YPF 2026",
    market: "Argentina",
    assetType: "ON",
    baseCurrency: "USD",
    price: 102.50,
    targetPrice: 110.00,
    marketCap: 0.5,
    peRatio: 0,
    pbRatio: 0,
    roe: 0,
    pegRatio: 0,
    dividendYield: 8.5,
    volume24h: 5,
    ema50: 101.80,
    ema200: 98.40,
    industry: "Energía",
    description: "Obligación Negociable de YPF. Préstamo a la empresa con devolución en dólares."
  },
  {
    id: "13",
    ticker: "S30J4",
    name: "LECAP Junio 2024",
    market: "Argentina",
    assetType: "Letra",
    baseCurrency: "ARS",
    price: 1.15,
    targetPrice: 1.25,
    marketCap: 200,
    peRatio: 0,
    pbRatio: 0,
    roe: 0,
    pegRatio: 0,
    dividendYield: 4.2, // Tasa mensual aprox
    volume24h: 800,
    ema50: 1.12,
    ema200: 1.05,
    industry: "Tesoro Nacional",
    description: "Letras del Tesoro a tasa fija. Ideal para colocar pesos a corto plazo de forma segura."
  },
  // GLOBAL - SECTOR EXPANSION
  {
    id: "g6",
    ticker: "JPM",
    name: "JPMorgan Chase & Co.",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 195.40,
    targetPrice: 215.00,
    marketCap: 560,
    peRatio: 11.8,
    pbRatio: 1.7,
    roe: 17.0,
    pegRatio: 1.2,
    dividendYield: 2.3,
    volume24h: 1200,
    ema50: 188.20,
    ema200: 175.40,
    industry: "Financials",
    description: "Uno de los bancos más grandes e importantes del mundo. Un pilar de estabilidad y dividendos."
  },
  {
    id: "g7",
    ticker: "UNH",
    name: "UnitedHealth Group",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 520.15,
    targetPrice: 580.00,
    marketCap: 480,
    peRatio: 22.4,
    pbRatio: 4.8,
    roe: 25.0,
    pegRatio: 1.5,
    dividendYield: 1.5,
    volume24h: 800,
    ema50: 505.40,
    ema200: 490.20,
    industry: "Healthcare",
    description: "Líder mundial en servicios de salud y seguros. Crecimiento constante."
  },
  {
    id: "g8",
    ticker: "XOM",
    name: "Exxon Mobil Corp.",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 118.30,
    targetPrice: 130.00,
    marketCap: 460,
    peRatio: 12.8,
    pbRatio: 2.1,
    roe: 18.0,
    pegRatio: 1.1,
    dividendYield: 3.2,
    volume24h: 2100,
    ema50: 112.40,
    ema200: 105.80,
    industry: "Energy",
    description: "Gigante del petróleo y gas. Ideal para dividendos y protección contra inflación."
  },
  {
    id: "g9",
    ticker: "COST",
    name: "Costco Wholesale",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 785.40,
    targetPrice: 850.00,
    marketCap: 350,
    peRatio: 48.0,
    pbRatio: 12.5,
    roe: 28.0,
    pegRatio: 2.5,
    dividendYield: 0.6,
    volume24h: 450,
    ema50: 750.20,
    ema200: 680.40,
    industry: "Consumer Defensive",
    description: "Modelo de suscripción único. Muy resiliente en crisis económicas."
  },
  // ARGENTINA - SECTOR EXPANSION
  {
    id: "a11",
    ticker: "TXAR",
    name: "Ternium Argentina",
    market: "Argentina",
    assetType: "Acción",
    baseCurrency: "ARS",
    price: 850.50,
    targetPrice: 1100.00,
    marketCap: 2.4,
    peRatio: 8.5,
    pbRatio: 1.4,
    roe: 19.0,
    pegRatio: 0.7,
    dividendYield: 4.5,
    volume24h: 1200,
    ema50: 820.40,
    ema200: 750.20,
    industry: "Basic Materials",
    description: "Líder en acero. Sus ganancias están muy atadas al valor del dólar."
  },
  {
    id: "a12",
    ticker: "LOMA",
    name: "Loma Negra",
    market: "Argentina",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 6.85, 
    targetPrice: 9.00,
    marketCap: 0.8,
    peRatio: 10.2,
    pbRatio: 1.1,
    roe: 12.0,
    pegRatio: 1.1,
    dividendYield: 3.0,
    volume24h: 400,
    ema50: 6.40,
    ema200: 5.90,
    industry: "Construction",
    description: "La cementera más grande del país. Clave para la obra pública y privada."
  },
  {
    id: "g10",
    ticker: "TSLA",
    name: "Tesla Inc.",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 175.20,
    targetPrice: 220.00,
    marketCap: 550,
    peRatio: 45.5,
    pbRatio: 8.2,
    roe: 22.0,
    pegRatio: 1.8,
    dividendYield: 0,
    volume24h: 8500,
    ema50: 185.40,
    ema200: 210.10,
    industry: "Consumer Cyclical",
    description: "Líder en autos eléctricos. Alta volatilidad pero gran potencial tecnológico."
  },
  {
    id: "g11",
    ticker: "WMT",
    name: "Walmart Inc.",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 60.15,
    targetPrice: 70.00,
    marketCap: 480,
    peRatio: 31.0,
    pbRatio: 6.5,
    roe: 15.0,
    pegRatio: 2.2,
    dividendYield: 1.4,
    volume24h: 1500,
    ema50: 58.20,
    ema200: 54.40,
    industry: "Consumer Defensive",
    description: "El gigante del retail. Sólido y defensivo para carteras conservadoras."
  },
  {
    id: "a13",
    ticker: "GD30",
    name: "Bonos Globales 2030",
    market: "Argentina",
    assetType: "Bono",
    baseCurrency: "ARS",
    price: 54120.00,
    targetPrice: 68000.00,
    marketCap: 12,
    peRatio: 0,
    pbRatio: 0,
    roe: 0,
    pegRatio: 0,
    dividendYield: 10.5,
    volume24h: 320,
    ema50: 53200.40,
    ema200: 50100.10,
    industry: "Estado Nacional",
    description: "Bono ley extranjera. Mayor seguridad jurídica que el AL30."
  },
  {
    id: "a14",
    ticker: "CRES",
    name: "Cresud S.A.",
    market: "Argentina",
    assetType: "Acción",
    baseCurrency: "ARS",
    price: 950.00,
    targetPrice: 1300.00,
    marketCap: 0.6,
    peRatio: 7.2,
    pbRatio: 0.9,
    roe: 14.0,
    pegRatio: 0.5,
    dividendYield: 2.5,
    volume24h: 210,
    ema50: 920.40,
    ema200: 850.10,
    industry: "Real Estate / Agribusiness",
    description: "Dueños de tierras y centros comerciales (IRSA). Activo real en Argentina."
  },
  // GLOBAL - EUROPE, ASIA & REST OF AMERICAS
  {
    id: "g12",
    ticker: "TSM",
    name: "Taiwan Semiconductor",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 145.30,
    targetPrice: 170.00,
    marketCap: 750,
    peRatio: 24.5,
    pbRatio: 6.2,
    roe: 28.0,
    pegRatio: 1.1,
    dividendYield: 1.2,
    volume24h: 3200,
    ema50: 140.20,
    ema200: 125.40,
    industry: "Semiconductors (Asia)",
    description: "El fabricante de chips más grande del mundo. Vital para toda la industria tecnológica global."
  },
  {
    id: "g13",
    ticker: "ASML",
    name: "ASML Holding",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 920.40,
    targetPrice: 1050.00,
    marketCap: 380,
    peRatio: 42.0,
    pbRatio: 22.1,
    roe: 45.0,
    pegRatio: 1.8,
    dividendYield: 0.7,
    volume24h: 450,
    ema50: 890.50,
    ema200: 820.10,
    industry: "Tech (Europe)",
    description: "Líder holandés en máquinas de litografía para chips. Monopolio tecnológico esencial."
  },
  {
    id: "g14",
    ticker: "BABA",
    name: "Alibaba Group",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 78.50,
    targetPrice: 110.00,
    marketCap: 190,
    peRatio: 12.4,
    pbRatio: 1.1,
    roe: 10.5,
    pegRatio: 0.8,
    dividendYield: 1.3,
    volume24h: 5200,
    ema50: 75.40,
    ema200: 82.10,
    industry: "E-Commerce (Asia)",
    description: "El gigante del comercio electrónico en China. Presenta una valuación muy atractiva por riesgo regulatorio."
  },
  {
    id: "g15",
    ticker: "SAP",
    name: "SAP SE",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 185.20,
    targetPrice: 210.00,
    marketCap: 210,
    peRatio: 28.1,
    pbRatio: 4.5,
    roe: 15.2,
    pegRatio: 1.5,
    dividendYield: 1.1,
    volume24h: 320,
    ema50: 178.40,
    ema200: 165.20,
    industry: "Software (Europe)",
    description: "Líder alemán en software de gestión empresarial. Referencia absoluta en Europa."
  },
  {
    id: "g16",
    ticker: "SONY",
    name: "Sony Group",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 85.40,
    targetPrice: 105.00,
    marketCap: 105,
    peRatio: 16.5,
    pbRatio: 1.9,
    roe: 12.8,
    pegRatio: 1.2,
    dividendYield: 0.6,
    volume24h: 850,
    ema50: 82.10,
    ema200: 88.40,
    industry: "Electronics (Asia)",
    description: "Conglomerado japonés líder en entretenimiento, consolas y sensores de imagen."
  },
  {
    id: "g17",
    ticker: "VALE",
    name: "Vale S.A.",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 12.15,
    targetPrice: 16.00,
    marketCap: 52,
    peRatio: 6.2,
    pbRatio: 1.4,
    roe: 22.5,
    pegRatio: 0.7,
    dividendYield: 7.2,
    volume24h: 9500,
    ema50: 13.10,
    ema200: 14.50,
    industry: "Materials (Americas)",
    description: "Gigante minero brasileño. Uno de los mayores productores de hierro en el mundo."
  },
  {
    id: "g18",
    ticker: "SHOP",
    name: "Shopify Inc.",
    market: "Global",
    assetType: "Acción",
    baseCurrency: "USD",
    price: 72.40,
    targetPrice: 95.00,
    marketCap: 93,
    peRatio: 65.0,
    pbRatio: 10.2,
    roe: 8.5,
    pegRatio: 2.5,
    dividendYield: 0,
    volume24h: 1200,
    ema50: 75.10,
    ema200: 68.40,
    industry: "E-Commerce (Americas)",
    description: "Plataforma canadiense líder para tiendas online. Gran crecimiento sostenido."
  }
];
